GitHub/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Event_name_or_type__c</fullName>
        <description>This field captures the Event name or type on the Request Event Support page on Communities</description>
        <label>Event name or type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	    <fields>
        <fullName>End_Time__c</fullName>
        <description>This field used in &quot;Request a Community Account Representative Visit&quot; type cases created from Communities Portal for End Time</description>
        <label>End Time</label>
        <picklist>
            <picklistValues>
                <fullName>12:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This field used in &quot;Request a Community Account Representative Visit&quot; type cases created from Communities Portal for Start Time</description>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>12:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>How_can_the_CAR_get_involved__c</fullName>
        <description>Describe how the Community Account Representative can get involved with the Move-In</description>
        <label>How can the CAR get involved?</label>
        <length>600</length>
        <type>LongTextArea</type>
    </fields>
	    <fields>
        <fullName>Number_of_Residents__c</fullName>
        <description>This field captures the count of residents attending the event on the Request Event Support page for Communities</description>
        <label>Number of Residents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
   <fields>
        <fullName>Event_Date__c</fullName>
        <description>This field captures the date of the event on the Request Event Support page for Communities</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

GitHub/src/objects/MDU_Property__c.object
<CustomObject>
</CustomObject>

GitHub/src/classes/CommunityManageRequestsControllerTest.cls
/**
*Class Name :       CommunityManageRequestsControllerTest
*CreatedBy :        Accenture
*CreatedDate :      24-Oct-2017
*Description :      Test class for CommunityManageRequestsController
*Modification History:
*/
@isTest
public class CommunityManageRequestsControllerTest {
	/***************************************
    * @MethodName: communityManageRequestsTest
    * @Author : Suchita, Accenture
    * @Date : 9-Oct-2017 
    * @Description : Test method
    * @UserStory : US1193371 -XCP Request Listing
    * @Return : void
    *****************************************/
    private static testMethod void communityManageRequestsTest(){
        
        TriggerSettings__c propertyTrigger = new TriggerSettings__c();
		propertyTrigger.Name = 'PROPERTY_TRIGGER';
		propertyTrigger.isActive__c = false;
		Database.insert(propertyTrigger); 
		
		TriggerSettings__c xfinityPropertyTrigger = new TriggerSettings__c();
		xfinityPropertyTrigger.Name = 'PROPERTYINSERT_TRIGGER';
		xfinityPropertyTrigger.isActive__c = false;
		Database.insert(xfinityPropertyTrigger); 
        
		Test.startTest();
		// Create test data
		MDU_Property__c  testProperty = TestDataUtility.createProperty();
		Database.insert(testProperty,true);		
		Case testCase = new Case();
		testCase.Status = 'Open';
		testCase.Property__c = testProperty.Id;
		testCase.Event_Date__c = system.today();
		testCase.End_Time__c = '1:00AM';
		testCase.Start_Time__c = '6:00AM';
		testCase.Number_of_Residents__c = 1;
		testCase.Event_name_or_type__c = 'Test';		   
		testCase.How_can_the_CAR_get_involved__c = 'Test Comment';           
		Map<String,Schema.RecordTypeInfo> caseRecordTypeInfos = Case.SObjectType.getDescribe().getRecordTypeInfosByName();
		testCase.RecordTypeId = caseRecordTypeInfos.get('Request Event Support').getRecordTypeId();
		database.insert(testCase,true);
           
		List<Case> caselst = CommunityManageRequestsController.fetchUsercases();
		List<String> allRequestTypelst = CommunityManageRequestsController.getAllRequestTypesForCommunityPortal();
		List<String> propertyValuelst = CommunityManageRequestsController.getPropertyValue();
                   
        Test.stopTest();
    }
}